# Shown as a "Sponsor" button on the repository page.
# https://docs.github.com/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: PatrickJnr
ko_fi: patrickjr
buy_me_a_coffee: PatrickJr
custom: ["https://www.paypal.me/PatrickJnrC"]
