/**
 * Website tests.
 *
 * The site is generated from the repository's own Markdown, so these tests
 * cover the generator and the invariants the built output has to hold: it
 * builds, it has no broken links, and the playground bundle is the genuine
 * interpreter rather than something that has drifted from it.
 */

import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { existsSync, readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import { describe, it } from "node:test";
import { fileURLToPath } from "node:url";

import { renderMarkdown, slug } from "../tools/markdown.ts";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const SITE = join(ROOT, "website");

/**
 * The website is a separate, private component and is not part of the public
 * repository. The Markdown converter it uses lives in `tools/` and is always
 * tested; everything that needs the site itself is skipped when it is absent,
 * so a clone without it still has a green suite.
 */
const HAS_SITE = existsSync(join(SITE, "src"));
const needsSite = { skip: HAS_SITE ? false : "no website/ in this checkout" };

function runTool(name: string): { code: number; out: string; err: string } {
  const result = spawnSync(process.execPath, [join(ROOT, "tools", name)], {
    cwd: ROOT,
    encoding: "utf8",
  });
  return { code: result.status ?? -1, out: result.stdout ?? "", err: result.stderr ?? "" };
}

describe("markdown converter", () => {
  it("renders headings with stable ids and anchors", () => {
    const { html, headings } = renderMarkdown("## Hello, flock!");
    assert.match(html, /<h2 id="hello-flock">/);
    assert.deepEqual(headings, [{ level: 2, text: "Hello, flock!", id: "hello-flock" }]);
  });

  it("de-duplicates repeated heading ids", () => {
    const { headings } = renderMarkdown("## Errors\n\n## Errors");
    assert.deepEqual(
      headings.map((heading) => heading.id),
      ["errors", "errors-2"],
    );
  });

  it("renders fenced code with a language class and a copy button", () => {
    const { html } = renderMarkdown('```baa\nbaa "hi"\n```');
    assert.match(html, /<code class="language-baa">baa &quot;hi&quot;<\/code>/);
    assert.match(html, /data-copy=""/);
  });

  it("does not format inside inline code", () => {
    const { html } = renderMarkdown("Use `a * b` and **bold**.");
    assert.match(html, /<code>a \* b<\/code>/);
    assert.match(html, /<strong>bold<\/strong>/);
  });

  it("drops HTML comments entirely rather than showing them", () => {
    const { html } = renderMarkdown(
      "<!-- Generated by tools/gen-docs.ts. Edit the source, not this file. -->\n\n# Title",
    );
    assert.ok(!html.includes("Generated by"), html);
    assert.ok(!html.includes("<!--"), html);
    assert.match(html, /<h1 id="title">Title<\/h1>/);
  });

  it("drops multi-line HTML comments", () => {
    const { html } = renderMarkdown("<!--\n  a note\n  over lines\n-->\n\nText.");
    assert.ok(!html.includes("a note"), html);
    assert.equal(html, "<p>Text.</p>");
  });

  it("escapes HTML in text and code", () => {
    const { html } = renderMarkdown("A `<script>` and a < sign");
    assert.ok(!html.includes("<script>"), html);
    assert.match(html, /&lt;script&gt;/);
  });

  it("renders tables, lists and blockquotes", () => {
    const table = renderMarkdown("| a | b |\n| --- | --- |\n| 1 | 2 |").html;
    assert.match(table, /<table>.*<th>a<\/th>.*<td>1<\/td>/s);

    const list = renderMarkdown("- one\n- two").html;
    assert.equal(list, "<ul><li>one</li><li>two</li></ul>");

    const checks = renderMarkdown("- [x] done\n- [ ] todo").html;
    assert.match(checks, /<input type="checkbox" disabled checked>/);

    const quote = renderMarkdown("> quoted").html;
    assert.match(quote, /<blockquote><p>quoted<\/p><\/blockquote>/);
  });

  it("escapes pipes inside table cells", () => {
    const { html } = renderMarkdown("| op |\n| --- |\n| a \\| b |");
    assert.match(html, /<td>a \| b<\/td>/);
  });

  it("rewrites links through the supplied function", () => {
    const { html } = renderMarkdown("[tour](LANGUAGE.md#loops)", {
      rewriteLink: (href) => (href.startsWith("LANGUAGE.md") ? "language.html#loops" : null),
    });
    assert.match(html, /<a href="language\.html#loops">tour<\/a>/);
  });

  it("marks external links as noopener", () => {
    const { html } = renderMarkdown("[x](https://example.com)");
    assert.match(html, /rel="noopener"/);
  });

  it("slugifies the way the anchors expect", () => {
    assert.equal(slug("`baa` run"), "baa-run");
    assert.equal(slug("Why TypeScript on Node"), "why-typescript-on-node");
    assert.equal(slug("BAA0xx: Syntax"), "baa0xx-syntax");
  });
});


/**
 * These run everywhere. The website is private, but the README is not, so the
 * images it embeds are committed and must resolve from a plain clone.
 */
describe("brand images", () => {
  const PUBLISHED = join(ROOT, "assets", "images");
  const NAMES = ["social.png", "social-dark.png", "logo.png", "logo-dark.png", "icon.png"];

  it("commits every brand PNG, so a plain clone can render the README", () => {
    for (const name of NAMES) {
      const path = join(PUBLISHED, name);
      assert.ok(existsSync(path), `missing assets/images/${name}; run node tools/render-assets.ts`);
      const bytes = readFileSync(path);
      assert.ok(bytes.length > 2000, `${name} is suspiciously small`);
      // PNG magic number, so a stray text file cannot pass for an image.
      assert.deepEqual(
        [...bytes.subarray(0, 4)],
        [0x89, 0x50, 0x4e, 0x47],
        `${name} is not a PNG`,
      );
    }
  });

  it("points the README at images that exist in the repository", () => {
    const readme = readFileSync(join(ROOT, "README.md"), "utf8");
    const pattern = /raw\.githubusercontent\.com\/[\w-]+\/[\w-]+\/HEAD\/([\w./-]+)/g;
    const refs = [...readme.matchAll(pattern)].map((match) => match[1]!);

    assert.ok(refs.length >= 3, `expected the README to embed repo images, found ${refs.length}`);
    for (const ref of new Set(refs)) {
      assert.ok(existsSync(join(ROOT, ref)), `README embeds ${ref}, which does not exist`);
    }

    // HEAD, not a branch name, so renaming the default branch cannot break them.
    const branchPinned = /raw\.githubusercontent\.com\/[\w-]+\/[\w-]+\/(main|master)\//;
    assert.equal(branchPinned.test(readme), false, "pin image URLs to HEAD, not a branch");
  });
});

describe("website build", needsSite, () => {
  it("builds without error", () => {
    const result = runTool("build-site.ts");
    assert.equal(result.code, 0, result.err);
    assert.match(result.out, /Built the site: \d+ pages/);
  });

  it("has no broken links or missing anchors", () => {
    const result = runTool("check-site.ts");
    assert.equal(result.code, 0, result.err);
    assert.match(result.out, /No broken links/);
  });

  it("produces every expected page", () => {
    for (const page of [
      "index.html",
      "playground.html",
      "404.html",
      "sitemap.xml",
      "robots.txt",
      "docs/index.html",
      "docs/language.html",
      "docs/spec.html",
      "docs/cli.html",
      "docs/stdlib.html",
      "docs/errors.html",
      "docs/faq.html",
      "docs/rust.html",
      "docs/search-index.json",
    ]) {
      assert.ok(existsSync(join(SITE, page)), `missing ${page}`);
    }
  });

  it("builds a usable search index", () => {
    const index = JSON.parse(
      readFileSync(join(SITE, "docs", "search-index.json"), "utf8"),
    ) as Array<{ title: string; page: string; url: string; text: string }>;
    assert.ok(index.length > 100, `only ${index.length} entries`);
    for (const entry of index.slice(0, 40)) {
      assert.ok(entry.title.length > 0);
      assert.ok(entry.url.length > 0);
    }
    assert.ok(
      index.some((entry) => entry.text.includes("BAA304") || entry.title.includes("Diagnostics")),
      "the diagnostic catalogue should be searchable",
    );
  });

  it("keeps the homepage free of placeholder text", () => {
    const html = readFileSync(join(SITE, "index.html"), "utf8");
    for (const bad of ["Lorem ipsum", "TODO", "FIXME", "coming soon", "PLACEHOLDER"]) {
      assert.ok(!html.toLowerCase().includes(bad.toLowerCase()), `homepage contains "${bad}"`);
    }
  });

  it("never leaks a generator note or any comment into a documentation page", () => {
    for (const file of readdirSync(join(SITE, "docs"))) {
      if (!file.endsWith(".html")) continue;
      const html = readFileSync(join(SITE, "docs", file), "utf8");
      const start = html.indexOf("<article");
      const body = html.slice(start, html.indexOf("</article>"));
      assert.ok(!body.includes("Generated by tools/"), `${file} shows the generator note`);
      assert.equal(/<!--/.test(body), false, `${file} contains an HTML comment`);
    }
  });

  it("ships brand assets that are self-contained and well formed", () => {
    for (const file of ["icon.svg", "logo.svg", "logo-dark.svg", "social.svg", "social-dark.svg"]) {
      const svg = readFileSync(join(SITE, "assets", file), "utf8");
      assert.equal((svg.match(/<svg/g) ?? []).length, 1, `${file}: expected one <svg>`);
      assert.equal((svg.match(/<\/svg>/g) ?? []).length, 1, `${file}: expected one </svg>`);
      assert.equal(svg.slice(svg.lastIndexOf("</svg>") + 6).trim(), "", `${file}: trailing content`);
      assert.equal(/https?:\/\//.test(svg.replace(/xmlns="[^"]*"/g, "")), false, `${file}: external reference`);
      assert.match(svg, /<title>/, `${file}: needs a <title> for accessibility`);
    }
  });

  it("references no external origin", () => {
    for (const page of ["index.html", "playground.html", "docs/language.html"]) {
      const html = readFileSync(join(SITE, page), "utf8");
      for (const match of html.matchAll(/(?:href|src)="(https?:\/\/[^"]+)"/g)) {
        const url = match[1]!;
        assert.ok(
          url.startsWith("https://github.com/") || url.startsWith("https://sheep.grimtech.co.uk"),
          `${page} loads or links to an unexpected origin: ${url}`,
        );
      }
      // Nothing may be *loaded* cross-origin. (A canonical <link> is a
      // declaration, not a fetch, so it is allowed to be absolute.)
      assert.equal(/<script[^>]+src="https?:/.test(html), false, `${page}: external script`);
      assert.equal(/<img[^>]+src="https?:/.test(html), false, `${page}: external image`);
      assert.equal(
        /<link[^>]+rel="(stylesheet|preload|prefetch|icon)"[^>]*href="https?:/.test(html),
        false,
        `${page}: external stylesheet or asset`,
      );
    }
  });
});

describe("playground bundle", needsSite, () => {
  const api = join(SITE, "assets", "baa", "api.js");

  it("exists and is the compiled interpreter", () => {
    assert.ok(existsSync(api), "run `npm run gen:playground`");
    const source = readFileSync(api, "utf8");
    assert.match(source, /export function run\(/);
    assert.match(source, /from "\.\/parser\/parser\.js"/);
  });

  it("has no unshimmed node: imports left", () => {
    const files = [
      join(SITE, "assets", "baa", "runtime", "host.js"),
      join(SITE, "assets", "baa", "stdlib", "pasture.js"),
      join(SITE, "assets", "baa", "stdlib", "shepherd.js"),
    ];
    for (const file of files) {
      const source = readFileSync(file, "utf8");
      assert.equal(/from "node:/.test(source), false, `${file} still imports a node: builtin`);
      assert.match(source, /\.\.\/(\.\.\/)*shims\//);
    }
  });

  it("runs a program, through the same code path the browser uses", async () => {
    const module = await import(`file://${api.split("\\").join("/")}`);
    const result = module.run(
      'import wool\nbaa wool.title_case("hello flock")\nbaa [1, 2, 3].map(fn(n) { return n * 2 })',
      "playground.baa",
      { seed: 7 },
    );
    assert.equal(result.ok, true, JSON.stringify(result.diagnostics));
    assert.equal(result.output, "Hello Flock\n[2, 4, 6]\n");
  });

  it("reports a diagnostic the same way the CLI does", async () => {
    const module = await import(`file://${api.split("\\").join("/")}`);
    const result = module.run("baa nope", "playground.baa");
    assert.equal(result.ok, false);
    assert.equal(result.diagnostics[0].code, "BAA102");
    assert.match(module.renderDiagnostic(result.diagnostics[0]), /playground\.baa:1:5/);
  });

  it("fails gracefully when the browser has no filesystem", async () => {
    const module = await import(`file://${api.split("\\").join("/")}`);
    const result = module.run('import pasture\nbaa pasture.read("/anything")', "playground.baa");
    assert.equal(result.ok, false);
    assert.equal(result.diagnostics[0].code, "BAA404");
  });
});
