// @generated by tools/gen-native-codes.ts from src/diagnostics/codes.ts.
// Do not edit. Run `npm run gen` after changing the catalogue.
//
// The native runtime raises a subset of these codes: it neither parses nor
// resolves, so every BAA0xx and BAA1xx is unreachable here. They are all
// included anyway, because a table that is a copy of the catalogue can be
// checked against it, and a hand-picked subset cannot.

/// `(code, woolly, plain)`, sorted by code.
pub const CATALOGUE: &[(&str, &str, &str)] = &[
    ("BAA001", "The sheep expected a closing {0} here.", "Expected a closing {0}."),
    ("BAA002", "This character isn't part of the Baa alphabet: {0}", "Unexpected character: {0}"),
    ("BAA003", "This string wandered off without a closing quote.", "Unterminated string literal."),
    ("BAA004", "This block comment never found its way back to the pen.", "Unterminated block comment."),
    ("BAA005", "This number is a bit malformed: {0}", "Malformed number literal: {0}"),
    ("BAA006", "The flock expected {0} here, but found {1}.", "Expected {0}, found {1}."),
    ("BAA007", "This escape sequence isn't one the sheep recognise: \\{0}", "Unknown escape sequence: \\{0}"),
    ("BAA008", "You can only put a name on the left of `=`. This isn't somewhere a value can graze.", "Invalid assignment target."),
    ("BAA009", "This interpolation `{{...}}` is empty: there's nothing to print.", "Empty interpolation expression."),
    ("BAA010", "This statement trails off before the sheep could finish reading it.", "Unexpected end of input."),
    ("BAA011", "This is nested deeper than the flock can follow: more than {0} levels.", "Nesting depth exceeds the limit of {0}."),
    ("BAA012", "This block string isn't laid out the way the sheep expect.", "Malformed block string literal."),
    ("BAA101", "`{0}` has already been counted in this pasture.", "`{0}` is already declared in this scope."),
    ("BAA102", "`{0}` is not part of the current flock.", "Undefined name `{0}`."),
    ("BAA103", "`{0}` was shorn with `const`: its value can't grow back.", "Cannot assign to constant `{0}`."),
    ("BAA104", "`return` only makes sense inside a function. Out here it just echoes across the meadow.", "`return` outside of a function."),
    ("BAA105", "`{0}` only makes sense inside a loop.", "`{0}` outside of a loop."),
    ("BAA106", "`{0}` is used here before the flock has been introduced to it.", "`{0}` is used before it is declared."),
    ("BAA201", "`{0}` was called with too many sheep: it takes {1} but got {2}.", "`{0}` expects {1} argument(s) but received {2}."),
    ("BAA202", "`{0}` was called with too few sheep: it takes {1} but got {2}.", "`{0}` expects {1} argument(s) but received {2}."),
    ("BAA203", "This parameter name `{0}` is used twice in the same function.", "Duplicate parameter name `{0}`."),
    ("BAA204", "This parameter list doesn't line up: {0}", "Invalid parameter list: {0}"),
    ("BAA301", "The flock wandered somewhere unexpected: {0}", "Runtime error: {0}"),
    ("BAA302", "You can't {0} {1} and {2}. These sheep don't herd together.", "Unsupported operand types for {0}: {1} and {2}."),
    ("BAA303", "`{0}` isn't something you can call. Only functions answer when called.", "`{0}` is not callable."),
    ("BAA304", "Index {0} is outside the fence: this {1} has length {2}.", "Index {0} out of range for {1} of length {2}."),
    ("BAA305", "There is no field called `{1}` on {0}.", "`{1}` is not a property of {0}."),
    ("BAA306", "Dividing by zero. Even sheep know better than that.", "Division by zero."),
    ("BAA307", "The flock has been counting too deep, the stack is full. (Is a function calling itself forever?)", "Maximum call depth exceeded."),
    ("BAA308", "Uncaught: {0}", "Uncaught exception: {0}"),
    ("BAA309", "You can't herd {0}: only arrays, maps, strings and ranges can be looped over.", "Cannot iterate over {0}."),
    ("BAA310", "This key isn't in the map: {0}", "Missing map key: {0}"),
    ("BAA311", "`{0}` expected {1} for argument {2}, but got {3}.", "`{0}`: argument {2} must be {1}, received {3}."),
    ("BAA312", "`{0}` was asked to build {1} items. The pen only holds {2}.", "`{0}`: requested size {1} exceeds the limit of {2}."),
    ("BAA313", "That gate is bolted: this run may not {0}.", "Capability denied: this run may not {0}."),
    ("BAA314", "`{0}` cannot use that pattern: {1}.", "`{0}`: unsupported pattern: {1}."),
    ("BAA401", "No module named `{0}` is grazing anywhere the shepherd can see.", "Module `{0}` could not be resolved."),
    ("BAA402", "This flock has wandered in a circle: {0}", "Circular import detected: {0}"),
    ("BAA403", "`{0}` doesn't export anything called `{1}`.", "Module `{0}` has no export named `{1}`."),
    ("BAA404", "Couldn't read the file: {0}", "Could not read file: {0}"),
    ("BAA405", "`baa.toml` is not well formed: {0}", "Invalid manifest: {0}"),
    ("BAA406", "`baa.lock` no longer describes this flock: {0}", "Lockfile is out of date: {0}"),
];

/// Message templates for one code, or `None` if the code is not an error.
pub fn lookup(code: &str) -> Option<(&'static str, &'static str)> {
    CATALOGUE
        .iter()
        .find(|(candidate, _, _)| *candidate == code)
        .map(|(_, woolly, plain)| (*woolly, *plain))
}

/// Fills `{0}`-style placeholders, leaving an unmatched one visible rather
/// than silently producing a sentence with a hole in it.
pub fn render(template: &str, args: &[String]) -> String {
    let mut out = String::with_capacity(template.len());
    let bytes: Vec<char> = template.chars().collect();
    let mut index = 0;
    while index < bytes.len() {
        if bytes[index] == '{' {
            let mut end = index + 1;
            while end < bytes.len() && bytes[end].is_ascii_digit() {
                end += 1;
            }
            if end > index + 1 && end < bytes.len() && bytes[end] == '}' {
                let slot: usize = bytes[index + 1..end].iter().collect::<String>().parse().unwrap_or(0);
                match args.get(slot) {
                    Some(value) => out.push_str(value),
                    None => out.push_str(&bytes[index..=end].iter().collect::<String>()),
                }
                index = end + 1;
                continue;
            }
        }
        out.push(bytes[index]);
        index += 1;
    }
    out
}
