/**
 * Builds `website/baa/`: the example site, arranged so a real web server can
 * execute it.
 *
 * The pages in `examples/site/` are the same ones `baa serve` runs locally.
 * What a host needs on top is small and entirely mechanical, which is why this
 * is a generator rather than a second copy of the site kept by hand:
 *
 *   - a shebang on every page that is a request entry point, because CGI runs
 *     the file itself rather than passing it to an interpreter;
 *   - the executable bit, which is set on upload rather than here;
 *   - an `.htaccess` turning on CGI for `.baa` and choosing the index page.
 *
 * The shebang has to name an interpreter that exists on the host, and that
 * path is different on every account. cPanel puts it under `nodevenv`, a VPS
 * usually has it on the PATH. Two variables set it, and they work together:
 * `BAA_CGI_BIN` is the directory `which baa` prints on the server, and
 * `BAA_CGI_DIR` is the absolute path this bundle will be uploaded to. With
 * both, the pages get a shebang naming a small wrapper that fixes PATH before
 * running `baa`. Without them they get `#!/usr/bin/env baa`, which is correct
 * only when CGI's own PATH already contains `baa` and `node`.
 *
 *     BAA_CGI_BIN=$(dirname $(which baa)) \
 *     BAA_CGI_DIR=/home/you/public_html/example.com/baa \
 *     node tools/build-cgi.ts
 *
 * Run that on the server, or in a shell that leaves absolute paths alone. Git
 * Bash on Windows rewrites a leading `/home/...` into `C:/Program Files/Git/
 * home/...` before Node ever sees it, which produces a shebang that is wrong
 * in a way nothing later notices; `MSYS_NO_PATHCONV=1` turns that off.
 */

import { copyFileSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const SOURCE = join(ROOT, "examples", "site");
const OUT = join(ROOT, "website", "baa");

/**
 * Directory holding `baa` and `node` on the host, from `dirname $(which baa)`.
 *
 * Both matter. `baa` is itself a Node script beginning `#!/usr/bin/env node`,
 * so running a page starts a chain: the page names `baa`, and `baa` asks the
 * environment for `node`. An interactive shell has this directory on its PATH
 * and the chain resolves; CGI runs with a minimal PATH and it does not, which
 * is a page that works from a terminal and returns 500 in a browser.
 */
const BIN = process.env.BAA_CGI_BIN ?? "";

/**
 * Absolute path the bundle will be uploaded to, so the shebang can name the
 * wrapper. A shebang is resolved against the process's working directory,
 * which for CGI is not something to rely on, so a relative one will not do.
 */
const DIR = process.env.BAA_CGI_DIR ?? "";

/**
 * Pages point at a wrapper rather than at `baa` directly, because the wrapper
 * is where PATH gets set before `baa` looks for `node`.
 *
 * Naming node and Baa's entry point together in the shebang would avoid the
 * extra file, but Linux reads at most 128 bytes of a shebang line and silently
 * truncates the rest, which two nvm paths comfortably exceed.
 */
const WRAPPER = "baa-cgi";
const SHEBANG = DIR === "" ? "#!/usr/bin/env baa" : `#!${DIR.replace(/\/$/, "")}/${WRAPPER}`;
const SHEBANG_LIMIT = 127;

function wrapperScript(): string {
  return `#!/bin/sh
# Generated by tools/build-cgi.ts.
#
# \`baa\` begins #!/usr/bin/env node, so it has to find node on PATH. CGI does
# not provide one that contains it. Setting PATH here is the whole job: without
# it the pages run from a shell and return 500 in a browser.
PATH="${BIN}:$PATH"
export PATH
exec "${BIN}/baa" "$@"
`;
}

/**
 * Pages a request can land on. `layout.baa` is missing on purpose: it is
 * imported by the others and produces no reply of its own, so it gets no
 * shebang. Without one the server cannot execute it, which is what stops a
 * direct request for it doing anything: no `.htaccess` rule is needed, and
 * a rule would risk the 500 that an unsupported directive causes.
 */
const PAGES = ["index.baa", "sheep.baa", "count.baa"];
const IMPORTED = ["layout.baa"];
const STATIC = ["style.css"];

const HTACCESS = `# Generated by tools/build-cgi.ts. Uploaded with the site.
#
# Three directives, all core. Nothing here depends on an optional module:
# an .htaccess containing a directive the server does not recognise makes
# every request in the directory a 500, including ones that would otherwise
# work, and the error looks like a fault in the page rather than in this file.
#
# In particular there is no \`Header\` (mod_headers) and no \`Require\`
# (Apache 2.4 authorisation), because neither is guaranteed on shared hosting
# and both fail this way when missing.

Options +ExecCGI
AddHandler cgi-script .baa
DirectoryIndex index.baa

# Modules a page imports are published as \`.baalib\` so the handler above never
# matches them: a \`.baa\` file with no shebang is one the server tries to run
# and cannot, and the 500 it returns quotes the file's full path on disk.
#
# \`RedirectMatch\` is mod_alias, which is as close to guaranteed as an Apache
# module gets, and refusing here means the source is not served either. If a
# host ignored it the result would be a readable example program rather than a
# broken directory, which is why it is this directive and not an authorisation
# one.
RedirectMatch 403 \\.baalib$
`;

/**
 * A page that answers the only question worth asking first: did the server run
 * this at all? A blank page, a download prompt or a 500 each mean something
 * different, and none of them is a Baa problem.
 */
const PROBE = `${SHEBANG}
/// Diagnostic page. Reports that CGI works and what it is running.
import gate
import shepherd
import wool

const rows = [
    ["Baa reached", "yes, this page is the output of a Baa program"],
    ["Server", shepherd.env("SERVER_SOFTWARE") ?? "not set"],
    ["Protocol", shepherd.env("SERVER_PROTOCOL") ?? "not set"],
    ["Method", gate.method()],
    ["Path below the script", gate.path()],
]

let body = "<h1>It works</h1><table>"
for row in rows {
    body += gate.format("<tr><th>%s</th><td>%s</td></tr>", row[0], row[1])
}
body += "</table><p><a href=\\"index.baa\\">Back to the example site</a></p>"

// Concatenated, not passed through \`gate.format\`: \`body\` is markup this
// page built, and format escapes what it interpolates. The escaping already
// happened where it belongs, on the values inside each row.
gate.html(
    "<!doctype html><html lang=\\"en\\"><head><meta charset=\\"utf-8\\">" +
    "<title>Baa CGI probe</title><link rel=\\"stylesheet\\" href=\\"style.css\\">" +
    "</head><body><main>" + body + "</main></body></html>",
)
`;

/**
 * Applications under `examples/apps/`, published at `<mount>/apps/<name>/`.
 *
 * A file is a page when it imports `gate`, because that is what a file needs
 * in order to answer a request at all. Anything else beside it is a module the
 * pages import. `tests/` is not published.
 *
 * Modules are published with a `.baalib` extension rather than `.baa`, and the
 * imports naming them are rewritten to match. That is not tidiness: it is the
 * only reliable way to keep the CGI handler off them.
 *
 * `AddHandler cgi-script .baa` applies to every `.baa` file in the directory
 * whatever its permissions are. A module has no shebang, so the server tries
 * to execute it, `execve` fails, and the 500 that comes back quotes the file's
 * full path on the server:
 *
 *     lscgid: execve():/home/you/public_html/example.com/baa/layout.baa
 *
 * Clearing the executable bit does not help, because the handler matches on
 * the extension. Renaming does, because it never matches. The `RedirectMatch`
 * in `.htaccess` then refuses the request rather than serving the source.
 *
 * If a host ignored that directive the result would be source disclosure of an
 * example program, which is a great deal better than the failure mode of an
 * unsupported access-control directive, which is every page in the directory
 * returning 500.
 */
function buildApps(): string[] {
  const appsRoot = join(ROOT, "examples", "apps");
  if (!existsSync(appsRoot)) return [];
  const built: string[] = [];

  for (const name of readdirSync(appsRoot).sort()) {
    const from = join(appsRoot, name);
    if (!statSync(from).isDirectory()) continue;
    const to = join(OUT, "apps", name);
    mkdirSync(to, { recursive: true });

    for (const entry of readdirSync(from).sort()) {
      const source = join(from, entry);
      if (statSync(source).isDirectory()) continue;
      if (!entry.endsWith(".baa")) {
        copyFileSync(source, join(to, entry));
        continue;
      }
      const text = readFileSync(source, "utf8").replace(/\r\n/g, "\n");
      const isPage = /^\s*import\s+gate\b/m.test(text);
      if (isPage) {
        writeFileSync(join(to, entry), `${SHEBANG}\n${rewriteModuleImports(text)}`, "utf8");
      } else {
        writeFileSync(join(to, moduleNameFor(entry)), text, "utf8");
      }
    }
    built.push(name);
  }
  return built;
}

/** `expression.baa` becomes `expression.baalib` in the published bundle. */
function moduleNameFor(entry: string): string {
  return `${entry.slice(0, -".baa".length)}.baalib`;
}

/**
 * Points a page's relative imports at the renamed modules.
 *
 * Baa resolves `import "./x.baalib"` by trying `x.baalib.baa` and then
 * `x.baalib`, so the renamed file is found with no change to the language, and
 * no change to the sources under `examples/`, which keep working under
 * `baa serve` exactly as they did.
 */
function rewriteModuleImports(text: string): string {
  return text.replace(
    /(import\s+(?:\{[^}]*\}\s+from\s+)?)"\.\/([A-Za-z0-9_.-]+)\.baa"/g,
    (whole, prefix: string, name: string) =>
      // A page never imports another page, so a relative import here names a
      // module. Left alone if one ever does.
      name === "index" ? whole : `${prefix}"./${name}.baalib"`,
  );
}

function build(): void {
  // The two variables only mean anything together. `BAA_CGI_DIR` alone points
  // every page at a wrapper that this run would not write, which is a bundle
  // that uploads cleanly and 500s on every request.
  if (DIR !== "" && BIN === "") {
    throw new Error(
      "BAA_CGI_DIR is set but BAA_CGI_BIN is not, so the pages would name a wrapper\n" +
        "that does not exist. Set both:\n" +
        "  BAA_CGI_BIN=$(dirname $(which baa)) BAA_CGI_DIR=... node tools/build-cgi.ts",
    );
  }

  if (SHEBANG.length > SHEBANG_LIMIT) {
    throw new Error(
      `the shebang is ${SHEBANG.length} bytes and Linux truncates at ${SHEBANG_LIMIT}:
  ${SHEBANG}
` +
        "Put the wrapper somewhere shorter and point BAA_CGI_DIR at that.",
    );
  }

  // A bundle built for a particular host carries a wrapper naming that host's
  // paths. `npm run gen` runs this with no environment set, which would
  // silently replace it with the generic PATH shebang and delete the wrapper —
  // a bundle that looks fine, uploads fine, and returns 500 for every page.
  // Say so rather than doing it quietly.
  if (existsSync(join(OUT, WRAPPER)) && BIN === "") {
    process.stdout.write(
      `website/baa/ was built for a specific host and this run has no BAA_CGI_BIN,\n` +
        `  so the ${WRAPPER} wrapper is being replaced by ${SHEBANG}.\n` +
        `  If that host needs the wrapper, rebuild with BAA_CGI_BIN and BAA_CGI_DIR set;\n` +
        `  website/baa/README.txt records the command.\n`,
    );
  }

  rmSync(OUT, { recursive: true, force: true });
  mkdirSync(OUT, { recursive: true });

  const available = new Set(readdirSync(SOURCE));
  for (const name of [...PAGES, ...IMPORTED, ...STATIC]) {
    if (!available.has(name)) throw new Error(`examples/site/${name} is missing`);
  }

  for (const name of PAGES) {
    const source = readFileSync(join(SOURCE, name), "utf8");
    if (source.startsWith("#!")) throw new Error(`${name} already has a shebang`);
    // LF endings: a CRLF after the shebang makes the kernel look for an
    // interpreter whose name ends in a carriage return, and the error that
    // produces names a file that looks correct.
    const page = `${SHEBANG}\n${rewriteModuleImports(source)}`.replace(/\r\n/g, "\n");
    writeFileSync(join(OUT, name), page, "utf8");
  }

  // Published as `.baalib` for the reason set out above `buildApps`: a `.baa`
  // file the handler picks up but cannot execute answers with a 500 quoting
  // its own path on disk.
  for (const name of IMPORTED) {
    const text = readFileSync(join(SOURCE, name), "utf8").replace(/\r\n/g, "\n");
    writeFileSync(join(OUT, moduleNameFor(name)), text, "utf8");
  }

  for (const name of STATIC) copyFileSync(join(SOURCE, name), join(OUT, name));

  writeFileSync(join(OUT, "probe.baa"), PROBE.replace(/\r\n/g, "\n"), "utf8");
  writeFileSync(join(OUT, ".htaccess"), HTACCESS.replace(/\r\n/g, "\n"), "utf8");
  writeFileSync(join(OUT, "README.txt"), readmeText(), "utf8");
  if (BIN !== "") writeFileSync(join(OUT, WRAPPER), wrapperScript(), "utf8");

  const apps = buildApps();

  process.stdout.write(
    `Built website/baa/: ${PAGES.length} pages, a probe, .htaccess` +
      (apps.length > 0 ? `, and ${apps.length} app(s): ${apps.join(", ")}` : "") +
      "\n" +
      `  shebang: ${SHEBANG}\n` +
      `  set BAA_CGI_BIN and BAA_CGI_DIR if that is not how \`baa\` is reached on the host\n`,
  );
}

function readmeText(): string {
  return `Deploying the Baa example site
==============================

These files are generated by tools/build-cgi.ts. Upload this directory to the
host, then do the two things a web server needs and a file copy does not.

1. Make the pages executable.

       chmod 755 *.baa

   CGI runs the file itself. Without the executable bit the server has nothing
   to run and will offer the source as a download instead.

2. Check the shebang names an interpreter that exists.

   These were generated with:

       ${SHEBANG}

   Run \`which baa\` on the server. If it prints something else, rebuild with

       BAA_CGI_BIN=$(dirname $(which baa)) \\
       BAA_CGI_DIR=${DIR === "" ? "/absolute/path/to/this/directory" : DIR} \\
       node tools/build-cgi.ts

   and upload again, or edit the first line of each .baa file by hand.

   On cPanel the path usually looks like
   /home/USER/nodevenv/APPNAME/22/bin/baa, and \`baa\` gets there with
   \`npm install -g baa-lang\` inside that Node environment.

Then open probe.baa first. It answers the only question worth asking at this
stage, which is whether the server ran a Baa program at all:

  - the probe page renders  ->  CGI works, everything else is ordinary debugging
  - the source is offered as a download  ->  the handler is not applied, or the
    executable bit is missing
  - 500 Internal Server Error  ->  the shebang points at nothing; the server
    error log names the path it tried
  - 403 Forbidden  ->  ExecCGI is off for this directory, which some hosts
    disallow in .htaccess and require through their control panel

If the page runs from the shell but the browser still returns 500, the script
is fine and the server is refusing to run it. Two causes account for almost
all of it:

  - a directive in .htaccess the server does not recognise. That makes every
    request in the directory a 500 regardless of the page, and the message
    looks like a fault in the program. Reduce .htaccess to the three
    directives generated here and add anything else one line at a time.

  - suEXEC refusing the script. It requires the file and the directory holding
    it to be owned by the account and writable by nobody else:

        ls -ld .          # the directory should be 755, not 775 or 777
        ls -l *.baa       # the pages should be 755

    A directory the group can write to is refused, and the reason appears in
    the suEXEC log rather than the error log.

Nothing here is stateful. Each request starts a process that remembers nothing,
which is the simplest thing that works and the reason it costs a process start
per page.
`;
}

build();
