/**
 * Builds `website/baa/`: the example site, arranged so a real web server can
 * execute it.
 *
 * The pages in `examples/site/` are the same ones `baa serve` runs locally.
 * What a host needs on top is small and entirely mechanical, which is why this
 * is a generator rather than a second copy of the site kept by hand:
 *
 *   - a shebang on every page that is a request entry point, because CGI runs
 *     the file itself rather than passing it to an interpreter;
 *   - the executable bit, which is set on upload rather than here;
 *   - an `.htaccess` turning on CGI for `.baa` and choosing the index page.
 *
 * The shebang has to name an interpreter that exists on the host, and that
 * path is different on every account. cPanel puts it under `nodevenv`, a VPS
 * usually has it on the PATH. Set `BAA_CGI_SHEBANG` to whatever `which baa`
 * prints on the server; the default assumes the PATH case.
 *
 *     BAA_CGI_SHEBANG='#!/home/you/nodevenv/site/22/bin/baa' node tools/build-cgi.ts
 */

import { copyFileSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const SOURCE = join(ROOT, "examples", "site");
const OUT = join(ROOT, "website", "baa");

/**
 * Directory holding `baa` and `node` on the host, from `dirname $(which baa)`.
 *
 * Both matter. `baa` is itself a Node script beginning `#!/usr/bin/env node`,
 * so running a page starts a chain: the page names `baa`, and `baa` asks the
 * environment for `node`. An interactive shell has this directory on its PATH
 * and the chain resolves; CGI runs with a minimal PATH and it does not, which
 * is a page that works from a terminal and returns 500 in a browser.
 */
const BIN = process.env.BAA_CGI_BIN ?? "";

/**
 * Absolute path the bundle will be uploaded to, so the shebang can name the
 * wrapper. A shebang is resolved against the process's working directory,
 * which for CGI is not something to rely on, so a relative one will not do.
 */
const DIR = process.env.BAA_CGI_DIR ?? "";

/**
 * Pages point at a wrapper rather than at `baa` directly, because the wrapper
 * is where PATH gets set before `baa` looks for `node`.
 *
 * Naming node and Baa's entry point together in the shebang would avoid the
 * extra file, but Linux reads at most 128 bytes of a shebang line and silently
 * truncates the rest, which two nvm paths comfortably exceed.
 */
const WRAPPER = "baa-cgi";
const SHEBANG = DIR === "" ? "#!/usr/bin/env baa" : `#!${DIR.replace(/\/$/, "")}/${WRAPPER}`;
const SHEBANG_LIMIT = 127;

function wrapperScript(): string {
  return `#!/bin/sh
# Generated by tools/build-cgi.ts.
#
# \`baa\` begins #!/usr/bin/env node, so it has to find node on PATH. CGI does
# not provide one that contains it. Setting PATH here is the whole job: without
# it the pages run from a shell and return 500 in a browser.
PATH="${BIN}:$PATH"
export PATH
exec "${BIN}/baa" "$@"
`;
}

/**
 * Pages a request can land on. `layout.baa` is missing on purpose: it is
 * imported by the others and produces no reply of its own, so it gets no
 * shebang. Without one the server cannot execute it, which is what stops a
 * direct request for it doing anything: no `.htaccess` rule is needed, and
 * a rule would risk the 500 that an unsupported directive causes.
 */
const PAGES = ["index.baa", "sheep.baa", "count.baa"];
const IMPORTED = ["layout.baa"];
const STATIC = ["style.css"];

const HTACCESS = `# Generated by tools/build-cgi.ts. Uploaded with the site.
#
# Three directives, all core. Nothing here depends on an optional module:
# an .htaccess containing a directive the server does not recognise makes
# every request in the directory a 500, including ones that would otherwise
# work, and the error looks like a fault in the page rather than in this file.
#
# In particular there is no \`Header\` (mod_headers) and no \`Require\`
# (Apache 2.4 authorisation), because neither is guaranteed on shared hosting
# and both fail this way when missing.

Options +ExecCGI
AddHandler cgi-script .baa
DirectoryIndex index.baa
`;

/**
 * A page that answers the only question worth asking first: did the server run
 * this at all? A blank page, a download prompt or a 500 each mean something
 * different, and none of them is a Baa problem.
 */
const PROBE = `${SHEBANG}
/// Diagnostic page. Reports that CGI works and what it is running.
import gate
import shepherd
import wool

const rows = [
    ["Baa reached", "yes, this page is the output of a Baa program"],
    ["Server", shepherd.env("SERVER_SOFTWARE") ?? "not set"],
    ["Protocol", shepherd.env("SERVER_PROTOCOL") ?? "not set"],
    ["Method", gate.method()],
    ["Path below the script", gate.path()],
]

let body = "<h1>It works</h1><table>"
for row in rows {
    body += gate.format("<tr><th>%s</th><td>%s</td></tr>", row[0], row[1])
}
body += "</table><p><a href=\\"index.baa\\">Back to the example site</a></p>"

// Concatenated, not passed through \`gate.format\`: \`body\` is markup this
// page built, and format escapes what it interpolates. The escaping already
// happened where it belongs, on the values inside each row.
gate.html(
    "<!doctype html><html lang=\\"en\\"><head><meta charset=\\"utf-8\\">" +
    "<title>Baa CGI probe</title><link rel=\\"stylesheet\\" href=\\"style.css\\">" +
    "</head><body><main>" + body + "</main></body></html>",
)
`;

function build(): void {
  if (SHEBANG.length > SHEBANG_LIMIT) {
    throw new Error(
      `the shebang is ${SHEBANG.length} bytes and Linux truncates at ${SHEBANG_LIMIT}:
  ${SHEBANG}
` +
        "Put the wrapper somewhere shorter and point BAA_CGI_DIR at that.",
    );
  }

  rmSync(OUT, { recursive: true, force: true });
  mkdirSync(OUT, { recursive: true });

  const available = new Set(readdirSync(SOURCE));
  for (const name of [...PAGES, ...IMPORTED, ...STATIC]) {
    if (!available.has(name)) throw new Error(`examples/site/${name} is missing`);
  }

  for (const name of PAGES) {
    const source = readFileSync(join(SOURCE, name), "utf8");
    if (source.startsWith("#!")) throw new Error(`${name} already has a shebang`);
    // LF endings: a CRLF after the shebang makes the kernel look for an
    // interpreter whose name ends in a carriage return, and the error that
    // produces names a file that looks correct.
    writeFileSync(join(OUT, name), `${SHEBANG}\n${source}`.replace(/\r\n/g, "\n"), "utf8");
  }

  for (const name of IMPORTED) {
    writeFileSync(join(OUT, name), readFileSync(join(SOURCE, name), "utf8").replace(/\r\n/g, "\n"), "utf8");
  }

  for (const name of STATIC) copyFileSync(join(SOURCE, name), join(OUT, name));

  writeFileSync(join(OUT, "probe.baa"), PROBE.replace(/\r\n/g, "\n"), "utf8");
  writeFileSync(join(OUT, ".htaccess"), HTACCESS.replace(/\r\n/g, "\n"), "utf8");
  writeFileSync(join(OUT, "README.txt"), readmeText(), "utf8");
  if (BIN !== "") writeFileSync(join(OUT, WRAPPER), wrapperScript(), "utf8");

  process.stdout.write(
    `Built website/baa/: ${PAGES.length} pages, a probe, and .htaccess\n` +
      `  shebang: ${SHEBANG}\n` +
      `  set BAA_CGI_SHEBANG if that is not where \`baa\` lives on the host\n`,
  );
}

function readmeText(): string {
  return `Deploying the Baa example site
==============================

These files are generated by tools/build-cgi.ts. Upload this directory to the
host, then do the two things a web server needs and a file copy does not.

1. Make the pages executable.

       chmod 755 *.baa

   CGI runs the file itself. Without the executable bit the server has nothing
   to run and will offer the source as a download instead.

2. Check the shebang names an interpreter that exists.

   These were generated with:

       ${SHEBANG}

   Run \`which baa\` on the server. If it prints something else, rebuild with
   BAA_CGI_SHEBANG set to it, or edit the first line of each .baa file.

   On cPanel the path usually looks like
   /home/USER/nodevenv/APPNAME/22/bin/baa, and \`baa\` gets there with
   \`npm install -g baa-lang\` inside that Node environment.

Then open probe.baa first. It answers the only question worth asking at this
stage, which is whether the server ran a Baa program at all:

  - the probe page renders  ->  CGI works, everything else is ordinary debugging
  - the source is offered as a download  ->  the handler is not applied, or the
    executable bit is missing
  - 500 Internal Server Error  ->  the shebang points at nothing; the server
    error log names the path it tried
  - 403 Forbidden  ->  ExecCGI is off for this directory, which some hosts
    disallow in .htaccess and require through their control panel

If the page runs from the shell but the browser still returns 500, the script
is fine and the server is refusing to run it. Two causes account for almost
all of it:

  - a directive in .htaccess the server does not recognise. That makes every
    request in the directory a 500 regardless of the page, and the message
    looks like a fault in the program. Reduce .htaccess to the three
    directives generated here and add anything else one line at a time.

  - suEXEC refusing the script. It requires the file and the directory holding
    it to be owned by the account and writable by nobody else:

        ls -ld .          # the directory should be 755, not 775 or 777
        ls -l *.baa       # the pages should be 755

    A directory the group can write to is refused, and the reason appears in
    the suEXEC log rather than the error log.

Nothing here is stateful. Each request starts a process that remembers nothing,
which is the simplest thing that works and the reason it costs a process start
per page.
`;
}

build();
