/**
 * Generates the native runtime's diagnostic catalogue from the reference one.
 *
 * Two implementations of the same language can disagree about many things; the
 * wording of an error should not be one of them. The catalogue in
 * `src/diagnostics/codes.ts` is the definition, and this writes the Rust
 * version of it. `npm run gen:check` fails if the generated file is stale, so a
 * new diagnostic reaches the native runtime in the same commit that adds it.
 *
 *     node tools/gen-native-codes.ts [--check]
 */

import { readFileSync, writeFileSync } from "node:fs";
import process from "node:process";
import { fileURLToPath } from "node:url";

import { CATALOGUE } from "../src/diagnostics/codes.ts";

const OUT = fileURLToPath(new URL("../rust/crates/baa-native/src/codes.rs", import.meta.url));

function rustString(text: string): string {
  return `"${text.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function generate(): string {
  const entries = Object.values(CATALOGUE)
    .filter((entry) => entry.severity === "error")
    .sort((a, b) => a.code.localeCompare(b.code));

  const rows = entries
    .map((entry) => `    (${rustString(entry.code)}, ${rustString(entry.woolly)}, ${rustString(entry.plain)}),`)
    .join("\n");

  return `// @generated by tools/gen-native-codes.ts from src/diagnostics/codes.ts.
// Do not edit. Run \`npm run gen\` after changing the catalogue.
//
// The native runtime raises a subset of these codes: it neither parses nor
// resolves, so every BAA0xx and BAA1xx is unreachable here. They are all
// included anyway, because a table that is a copy of the catalogue can be
// checked against it, and a hand-picked subset cannot.

/// \`(code, woolly, plain)\`, sorted by code.
pub const CATALOGUE: &[(&str, &str, &str)] = &[
${rows}
];

/// Message templates for one code, or \`None\` if the code is not an error.
pub fn lookup(code: &str) -> Option<(&'static str, &'static str)> {
    CATALOGUE
        .iter()
        .find(|(candidate, _, _)| *candidate == code)
        .map(|(_, woolly, plain)| (*woolly, *plain))
}

/// Fills \`{0}\`-style placeholders, leaving an unmatched one visible rather
/// than silently producing a sentence with a hole in it.
pub fn render(template: &str, args: &[String]) -> String {
    let mut out = String::with_capacity(template.len());
    let bytes: Vec<char> = template.chars().collect();
    let mut index = 0;
    while index < bytes.len() {
        if bytes[index] == '{' {
            let mut end = index + 1;
            while end < bytes.len() && bytes[end].is_ascii_digit() {
                end += 1;
            }
            if end > index + 1 && end < bytes.len() && bytes[end] == '}' {
                let slot: usize = bytes[index + 1..end].iter().collect::<String>().parse().unwrap_or(0);
                match args.get(slot) {
                    Some(value) => out.push_str(value),
                    None => out.push_str(&bytes[index..=end].iter().collect::<String>()),
                }
                index = end + 1;
                continue;
            }
        }
        out.push(bytes[index]);
        index += 1;
    }
    out
}
`;
}

const generated = generate();
const check = process.argv.includes("--check");

if (check) {
  let existing = "";
  try {
    existing = readFileSync(OUT, "utf8");
  } catch {
    existing = "";
  }
  if (existing.replace(/\r\n/g, "\n") !== generated) {
    process.stderr.write("rust/crates/baa-native/src/codes.rs is stale. Run `npm run gen`.\n");
    process.exit(1);
  }
  process.stdout.write("native codes up to date\n");
} else {
  writeFileSync(OUT, generated, "utf8");
  process.stdout.write(`wrote ${OUT}\n`);
}
