/**
 * Generate `docs/stdlib.md` and `docs/errors.md` from the implementation.
 *
 *     node tools/gen-docs.ts            # write the files
 *     node tools/gen-docs.ts --check    # exit 1 if they are out of date
 *
 * These two documents are the ones most likely to drift, because they list
 * things a contributor adds in code. Generating them means the docs cannot be
 * wrong without the test suite noticing.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

import { ALL_CODES, CATALOGUE } from "../src/diagnostics/codes.ts";
import { createCapturingHost } from "../src/runtime/host.ts";
import { Interpreter } from "../src/runtime/interpreter.ts";
import { methodDocs } from "../src/runtime/methods.ts";
import { formatNumber, NativeFunction } from "../src/runtime/values.ts";
import { STDLIB_MODULES, STDLIB_SUMMARY } from "../src/stdlib/index.ts";
import { preludeDocs } from "../src/stdlib/prelude.ts";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const DOCS = join(ROOT, "docs");

/**
 * Constants whose value is a property of the machine, not of Baa.
 *
 * Printing what they happen to be on the generating machine made the output
 * depend on who ran the generator: the committed table said `win32`, so
 * `--check` failed on Linux, and every reader not on Windows was told
 * something untrue. They are described instead.
 */
const HOST_DEPENDENT: Readonly<Record<string, string>> = {
  "shepherd.PLATFORM": "the host platform: `win32`, `linux`, `darwin`, ...",
  "shepherd.ARCH": "the host architecture: `x64`, `arm64`, ...",
  "pasture.SEPARATOR": "the host path separator: `\\` on Windows, `/` elsewhere",
};

const GENERATED_NOTE =
  "<!-- Generated by tools/gen-docs.ts. Edit the source, not this file. -->";

function arity(min: number, max: number): string {
  if (max >= Number.MAX_SAFE_INTEGER) return `${min}+`;
  return min === max ? String(min) : `${min}–${max}`;
}

function escapePipes(text: string): string {
  return text.replace(/\|/g, "\\|");
}

// --------------------------------------------------------------------------
// docs/stdlib.md
// --------------------------------------------------------------------------

export function renderStdlib(): string {
  const interpreter = new Interpreter({ host: createCapturingHost() });
  const out: string[] = [];

  out.push(GENERATED_NOTE);
  out.push("");
  out.push("# Standard library reference");
  out.push("");
  out.push(
    "Every function Baa ships with. Module names are sheep-themed; the functions inside them are not: an API you have to remember at 2am is no place for a joke.",
  );
  out.push("");
  out.push("- [The prelude](#the-prelude), available without an import");
  out.push("- [Methods](#methods), available on values themselves");
  for (const name of STDLIB_MODULES) {
    out.push(`- [\`${name}\`](#${name}): ${STDLIB_SUMMARY[name] ?? ""}`);
  }
  out.push("");
  out.push("---");
  out.push("");

  out.push("## The prelude");
  out.push("");
  out.push("These names are in scope in every file, with no import. A local declaration may shadow any of them.");
  out.push("");
  out.push("| Function | Arguments | Description |");
  out.push("| --- | --- | --- |");
  for (const entry of preludeDocs()) {
    out.push(`| \`${entry.name}\` | ${entry.arity} | ${escapePipes(entry.doc)} |`);
  }
  out.push("");

  out.push("## Methods");
  out.push("");
  out.push(
    "Methods are looked up on the value itself and are ordinary first-class functions: `const shout = \"baa\".upper` then `shout()` works.",
  );
  out.push("");
  const rows = methodDocs();
  const types = [...new Set(rows.map((row) => row.type))];
  for (const type of types) {
    const heading = type === "any" ? "On every value" : `On \`${type}\``;
    out.push(`### ${heading}`);
    out.push("");
    out.push("| Method | Arguments | Description |");
    out.push("| --- | --- | --- |");
    for (const row of rows.filter((r) => r.type === type)) {
      out.push(`| \`${row.name}\` | ${row.arity} | ${escapePipes(row.doc)} |`);
    }
    out.push("");
  }

  for (const name of STDLIB_MODULES) {
    const module = interpreter.loadModule(name, false, {
      file: { path: "<docs>", text: "" } as never,
      start: 0,
      end: 0,
    });
    out.push(`## \`${name}\``);
    out.push("");
    out.push(STDLIB_SUMMARY[name] ?? "");
    out.push("");
    out.push("```baa");
    out.push(`import ${name}`);
    out.push("```");
    out.push("");

    const constants: string[] = [];
    const functions: string[] = [];
    for (const [key, value] of module.exports) {
      if (value instanceof NativeFunction) {
        functions.push(
          `| \`${name}.${key}\` | ${arity(value.minArgs, value.maxArgs)} | ${escapePipes(value.doc)} |`,
        );
      } else {
        const described = HOST_DEPENDENT[`${name}.${key}`];
        const shown =
          described ??
          `\`${typeof value === "number" ? formatNumber(value) : String(value)}\``;
        constants.push(`| \`${name}.${key}\` | ${shown} |`);
      }
    }

    if (constants.length > 0) {
      out.push("| Constant | Value |");
      out.push("| --- | --- |");
      out.push(...constants);
      out.push("");
    }
    if (functions.length > 0) {
      out.push("| Function | Arguments | Description |");
      out.push("| --- | --- | --- |");
      out.push(...functions);
      out.push("");
    }
  }

  out.push("---");
  out.push("");
  out.push(
    "Missing something? The standard library is deliberately small: see [ROADMAP.md](../ROADMAP.md) for what is planned, and [CONTRIBUTING.md](../CONTRIBUTING.md) for how to add it.",
  );
  out.push("");
  return out.join("\n");
}

// --------------------------------------------------------------------------
// docs/errors.md
// --------------------------------------------------------------------------

const RANGES: Array<[string, string, string]> = [
  ["BAA0", "Syntax", "The shape of the source is wrong. Reported before anything runs."],
  ["BAA1", "Names and scope", "Something is not declared, is declared twice, or cannot be assigned."],
  ["BAA2", "Calls", "A function was called with the wrong number of arguments, or declared badly."],
  ["BAA3", "Runtime", "The program was valid but something went wrong while it ran."],
  ["BAA4", "Modules and projects", "An import, a manifest or a file could not be resolved."],
  ["BAA9", "Lints", "Warnings from `baa lint`. These never make a program invalid."],
];

export function renderErrors(): string {
  const out: string[] = [];
  out.push(GENERATED_NOTE);
  out.push("");
  out.push("# Diagnostic catalogue");
  out.push("");
  out.push(
    "Every message Baa can produce, with a stable code. Codes never change meaning: if `BAA102` means one thing today, it means the same thing in every future version. New diagnostics take new numbers.",
  );
  out.push("");
  out.push(
    "Each entry has two wordings. The **default** is sheep-flavoured. The **plain** wording is used under `--no-baa`, `BAA_NO_BAA=1` or when `CI` is set, and carries exactly the same information: the code, the severity and the source span are identical either way.",
  );
  out.push("");
  out.push("Placeholders like `{0}` are filled in with the specifics at the point of failure.");
  out.push("");

  for (const [prefix, title, description] of RANGES) {
    const codes = ALL_CODES.filter((code) => code.startsWith(prefix));
    if (codes.length === 0) continue;
    out.push(`## ${prefix}xx, ${title}`);
    out.push("");
    out.push(description);
    out.push("");
    out.push("| Code | Severity | Default wording | Plain wording |");
    out.push("| --- | --- | --- | --- |");
    for (const code of codes) {
      const spec = CATALOGUE[code];
      out.push(
        `| \`${code}\` | ${spec.severity} | ${escapePipes(spec.woolly)} | ${escapePipes(spec.plain)} |`,
      );
    }
    out.push("");
  }

  out.push("## Silencing a lint");
  out.push("");
  out.push("Lints (`BAA9xx`) can be turned off per rule:");
  out.push("");
  out.push("```bash");
  out.push("baa lint --disable BAA905 .");
  out.push("```");
  out.push("");
  out.push(
    "For the unused-name lints there is a lighter option: prefix the name with `_`. `const _deliberately_unused = 1` is never reported.",
  );
  out.push("");
  out.push("## Catching a runtime error");
  out.push("");
  out.push(
    "`BAA3xx` errors are catchable. The value bound by `catch` is a map with `code`, `message`, `file`, `line` and `column`:",
  );
  out.push("");
  out.push("```baa");
  out.push("try {");
  out.push("    baa flock[99]");
  out.push("} catch problem {");
  out.push('    baa "{problem.code} at line {problem.line}"');
  out.push("}");
  out.push("```");
  out.push("");
  return out.join("\n");
}

// --------------------------------------------------------------------------

const targets: Array<[string, string]> = [
  [join(DOCS, "stdlib.md"), renderStdlib()],
  [join(DOCS, "errors.md"), renderErrors()],
];

const check = process.argv.includes("--check");
let stale = 0;

for (const [path, content] of targets) {
  let existing: string | null = null;
  try {
    existing = readFileSync(path, "utf8").replace(/\r\n?/g, "\n");
  } catch {
    existing = null;
  }
  if (existing === content) continue;
  if (check) {
    process.stderr.write(`${path} is out of date: run \`node tools/gen-docs.ts\`\n`);
    stale++;
  } else {
    writeFileSync(path, content, "utf8");
    process.stdout.write(`wrote ${path}\n`);
  }
}

if (check && stale > 0) process.exitCode = 1;
